# This workflow triages pull requests that modify YAML and Assets files.
#
# To use it, configure a .yamllint file with the necessary Lint settings.
#
# The workflow runs Python scripts to validate content and prevent issues.

---
name: Tests
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install packages
        run: pip3 install -r tests/requirements.txt
      - name: Run yamllint
        run: yamllint --strict .
      - name: Run tests
        run: python3 tests/main.py
